name: GitHub Actions Demo
on: [push]
jobs:
  Facets-Int-Builds:
    runs-on: ubuntu-latest
    steps:
         - name: checkout code 1..
           uses: actions/checkout@v2
         - name: running interactive software
           run: ansible-playbook -i hosts interactive_pb.yml
              
  Facets-Batch-Builds:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was event..."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "task1"
      - name: test2        
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: batch_pb.yml
          directory: ./
          inventory: |
           [win]
              10.44.240.245
              10.44.241.171
              10.44.241.172
              10.44.240.246
              10.44.241.173
              10.34.243.166
              10.44.241.174

           [win:vars]
              ansible_connection=winrm
              ansible_port=5986
              ansible_winrm_server_cert_validation=ignore
              ansible_winrm_transport=credssp
              ansible_user=dev\admatan01
              ansible_password=Poameiri21!@
        

        

  

     
      
        
            
        
  

  
     
   



