name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: windows-2019
    steps:
      - run: echo "🎉 The job was event."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "hello"
        working-directory: ./cicd
      - run: ansible-playbook -i hosts batch_pb.yml
        
        
  

  
     
   



