name: facets installation
on:
   push:
     branches: main    
jobs:
 build:
  runs-on: windows-2019
  steps:
    - uses: actions/checkout@v2

    - name: install batch_build
    - run: echo install batch core

    - name: powershell
    - working-directory: ./cicd
    - run: ansible-playbook interactive_pb.yml -i hosts
   



