name: GitHub Actions Demo
on: [push]
jobs:
  Facets-Batch-Builds:
    runs-on: windows-2019
    steps:
      - run: echo "🎉 The job was event."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "task1"
      - name: test2
        uses: dawidd6@/action-ansible-playbook@v.2.5.0
        with:
          playbook: cicd/batch_pb.yml
          directory: ./
          inventory: hosts
        
#        working-directory: .
#      - run: ansible-playbook -i hosts batch_pb.yml
      
        
            
        
  

  
     
   



